### ISSUE TITLE
Simplification 

### ISSUE THREAD

**Issue by Hannaes** [h5p/h5p-text-grouping#1]
https://github.com/h5p/h5p-text-grouping/blob/56c1df2530fbf340270370e56114601a1f73a0cd/src/components/Main.js#L35

Creating an issue as it was not clear to see exactly where this was added. 

I think this could be simplified and maybe also improved performance for. Here we have many loops for each arrays. 

Couldn't we just set appliedCategoryAssignment to the temporary one?  
@nicklasbekkevold

**Comment by nicklasbekkevold** [comment]
Yes, the problem was that the ordering of the items would change when items were selected and unselected. @seliash fixed this by modifying applyCategoryAssignement as you pointed out. I also believe we could simplify things.
